### PR TITLE
Bug fixed - white safe-area on the top of viewport when built by XCode9

### PR DESCRIPTION
**Pull request by gameboyVito**
By default, the wkwebivew will have a white statusbar inset on the top of your webview. Even if you have set the viewport by yourself, like viewport-fit=cover. It will still, have white space inset on the bottom. This PR is going to fix this issue.

### CODE REVIEW

**Comment by gameboyVito** [comment]
Here's a post reporting this issue, same as the WKWebView if you are building with iOS11 baseSDK.
https://stackoverflow.com/questions/45662388/ios-11-uiwebview-pop-down-by-status-bar

**Comment by gameboyVito** [comment]
Can anyone review this PR?

**Comment by insraq** [comment]
This change is introduced together with the safe area change and to replace `automaticallyAdjustsScrollViewInsets`. I am not sure hard code a NO/UIScrollViewContentInsetAdjustmentNever is a good idea as it might break existing code and iPhone X

**Comment by oblador** [comment]
IMHO, we should implement [contentInsetAdjustmentBehavior](https://facebook.github.io/react-native/docs/scrollview.html#contentinsetadjustmentbehavior) instead.

**Comment by insraq** [comment]
This should have been fixed by 33fb78f315f1409d6ee6d14f77e29a10e9a73436

contentInsetAdjustmentBehavior has been implemented.

**Pull request closed without merging**
