### PR TITLE
Store original postMessage

### PR DESCRIPTION
**Pull request by fchasen**
The work around for waiting for window.originalPostMessage outlined in
https://github.com/facebook/react-native/issues/11594 is likely pretty common and is also needed for with wkwebview.

This stores the original native postMessage as originalPostMessage, and checks that is hasn't been overwritten in development from RN Webview code here: https://github.com/facebook/react-native/blob/26684cf3adf4094eb6c405d345a75bf8c7c0bf88/React/Views/RCTWebView.m#L313

Also switches to calling `window.webkit.messageHandlers.reactNative.postMessage` with `apply` so that all arguments can be passed in.

### CODE REVIEW

**Comment by mmorier** [comment]
This commit cause some issues with post messaging. It seems create a different behavior between this component and RN WebView component. Since this commit, `onMessage` on `WKWebView` is not called. I have no problem with this handler on `WebView`.

Can we rollback it?

**Comment by insraq** [comment]
@mmorier I think most of this PR's code is derived from React Native's Webview. Not sure why you have problems. I did make a commit that address @alexgsummer 's concern. (44f7c36b6c589b3749a2fa2ae62c12a4a229c96b)

**Comment by fchasen** [comment]
I'll check if the postMessage / onMessage code has been updated in newer RN versions.

@mmorier what version of RN did you test with and do you have an example of the postMessage calls that are failing?

**Comment by mmorier** [comment]
I used react-native:0.55.2. My postMessage is very simple like that `{"id":1, "method":"getCurrentPosition"}`.

**Pull request merged**
