### PR TITLE
added support for allowsLinkPreview property

### PR DESCRIPTION
**Pull request by alexisbronchart**
I just added the allowsLinkPreview prop + its mapping.

### CODE REVIEW

**Comment by andreyslyusar** [comment]
`allowsLinkPreview` is available only starting from iOS 9 (https://developer.apple.com/documentation/webkit/wkwebview/1415000-allowslinkpreview), so running iOS 8 it will crash with exception: `-[WKWebView setAllowsLinkPreview:]: unrecognized selector sent to instance`.

**Comment by alexisbronchart** [comment]
Sorry I meant to only commit the "if @available" change but I messed with my local git history. Thanks for merging anyway 👍

**Comment by jackdewhurst** [comment]
Any news on if/when this will be fixed to avoid having to do an OS version check?

**Comment by insraq** [comment]
@jackdewhurst AFAIK It should work for iOS >= 9

**Comment by jackdewhurst** [comment]
Yeah but I can only include the prop on iOS 9 and above. So need to check iOS version and setup the WKWebview differently depending on it.

I would expect `allowsLinkPreview` prop to be ignored on OS versions lower than 9 but it throws an exception

**Comment by insraq** [comment]
I should just be a no-op on iOS < 9 -- should not throw any exceptions.

**Comment by jackdewhurst** [comment]
You're right. I can get it working like this:

```
const iOSVersion = parseInt(Platform.Version, 10);

<WKWebView>
    allowsLinkPreview={(Platform.OS === "iOS" && iOSVersion >= 9)? true : null}
</WKWebView>
```

Is there a more elegant solution I'm missing?

**Comment by insraq** [comment]
This should work?
```
<WKWebView>
    allowsLinkPreview={true}
</WKWebView>
```
For iOS < 9, it will get ignored.

**Comment by jackdewhurst** [comment]
This is what I'm reporting. The above code you posted does not work on iOS > 9 with version 1.14.0 of `react-native-wkwebview`.

```
<WKWebView>
    allowsLinkPreview={true}
</WKWebView>
```

throws an exception when running on the Xcode simulator with iOS version 8.4.

**Pull request merged**
