### PR TITLE
Add injectJavaScript support.

### PR DESCRIPTION
**Pull request by iineva**

### CODE REVIEW

**Comment by shirakaba** [comment]
Decided to inline the screenshot (demonstrating proof of the PR working) I mentioned in the summary:

per-frame js injection working

@insraq This is an exceptional feature addition. Per-iframe injection, and strict control of when to inject JS with relation to page load, was pretty much the core function used when developing a fully-native iOS app of mine, so I'd love to see this ported to React Native. I see no problems in the code, and it exposes the UserContentController API in a very React-friendly manner; what is needed to get this merged in?

**Comment by shirakaba** [comment]
I just noticed that there is an older PR for this #71 , which accepted a `userScript` prop instead, but the PR suffered from `userScript` being immutable after the first render.

I have found that this PR does not suffer from this: Any change to the `injectJavaScript` or `injectedJavaScript` props *are* reflected upon the next page load.

**Comment by dodgecm** [comment]
Looking forward to seeing this merged in; this would probably allow the AJAX cookies hack I submitted to be built entirely in JS with the help of react-native-cookies or something like that.

**Comment by insraq** [comment]
This PR has been merged. However, it broke the `postMessage` bridge. 29588d4144940864126c689c4c400eb215f72adf should have fixed it.

**Pull request merged**
