### PR TITLE
Improve scrollview

### PR DESCRIPTION
**Pull request by MasahiroMorita**
This improvement makes scrollView inside of webView not slide up in order to make the input fields visible when the input fields is focused and keyboard appears.

This patch is inspired by this article:
https://stackoverflow.com/questions/15926260/set-uiwebview-content-not-to-move-when-keyboard-is-shown

### CODE REVIEW

**Comment by insraq** [comment]
Thanks for the PR. However, this is not the default behavior and might not be desired by all users. Therefore, if we are going to merge this PR, it should be added as an option and turned off by default.

**Comment by vomchik** [comment]
@MasahiroMorita Hi, do you have time to resolve conflict and make this feature as optional?

**Comment by MasahiroMorita** [comment]
@insraq I think this behaviour should be default.
It is very reasonable behaviour to inhibit to slide a content of webview  up when an input field within the content has got focused, if the webview is placed with scrollEnable={false}.

You will see very strange behaviour when you put a webview with its html content including text input field and scrollEnabled={false} without my patch in your app. Then you touch the text input field in the webview, the content inside the webview will get slide up to be able to use the keyboard. However, in that case, the webview's scroll is disabled, so you can't restore scroll position any longer.

@vomchik Ok, I will send a new PR later.

**Comment by vomchik** [comment]
@MasahiroMorita I agree with you it should be the default behavior.

**Comment by insraq** [comment]
@MasahiroMorita I think it makes sense it have this if `scrollEnabled=false`. But the current PR does not seem to check that. Also, please exclude the `package.json` from PR to avoid conflict when I release to `npm`.

**Comment by MasahiroMorita** [comment]
I closed this PR, and sent a new PR to support the latest version of WkWebview.
https://github.com/CRAlpha/react-native-wkwebview/pull/135

**Pull request closed without merging**
