### PR TITLE
WKUserScript support

### PR DESCRIPTION
**Pull request by oblador**
In my use case I need to inject code to some external iframes in my web view, however that's only possible by adding a `WKUserScript`. 

This PR adds this functionality by adding a `userScript` prop, but since this needs to be injected upon the intialization of the `WKWebView` and cannot be mutated later, a refactor of the init code was needed and some of the prop setters. It's not the most elegant solution, but that's mostly due to the inflexible API of `WKWebView` and that the react props not being available at init.

### CODE REVIEW

**Comment by insraq** [comment]
I completely understand the problem wrt. the init code and react props. I'm wondering are there any better solutions at all?

**Comment by oblador** [comment]
Problem is that the `config` dict cannot be mutated after initialization. Don't know a good way of circumventing this besides this approach, can you think of any?

**Comment by insraq** [comment]
I am not aware of any. However, given this is quite common in Cocoa API, I'm surprised there has not been a better solution.

**Comment by oblador** [comment]
Agreed, it's quite frustrating knowing that react has all the props but will only let you know about them after the fact :-)

**Comment by oblador** [comment]
@insraq What are your thoughts? Should we close the PR or do you have an alternative? Going on a trip tomorrow, so not likely I'll be able to make any big changes soon though.

**Comment by oblador** [comment]
Back from trip, LMK how you want to proceed. Happy to close this PR if you don't think it's a good idea.

**Comment by maxstoller** [comment]
@oblador This is fantastic, thanks for the PR. Any plans to implement the WKScriptMessageHandler protocol? Looking for a way to pass messages to an iframe inside a WKWebView. Thanks again.

**Comment by insraq** [comment]
@oblador Apologize for the (very) late reply. I have added you as a collaborator, feel free to move this PR forward.

**Comment by jzbrooks** [comment]
Hey @oblador, I'm interested in WKUserScript support also. Do you think there is any chance you will merge this PR soon? Thanks!

**Comment by oblador** [comment]
@jzbrooks I have a different and cleaner approach in my private fork that I'll try to update this PR whenever I have time.

**Comment by jzbrooks** [comment]
@oblador Great. Thanks!

**Comment by dodgecm** [comment]
@oblador any chance you could update the PR with your cleaner approach?  it would be really useful for something i'm trying to build atm.

**Comment by shirakaba** [comment]
@jzbrooks @dodgecm see also PR #116 if you're still interested in this feature!

**Pull request closed without merging**
